apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm.json: |
    {
      "realm": "myrealm",
      "displayName": "My Realm",
      "enabled": true,
      "sslRequired": "external",
      "registrationAllowed": false,
      "clients": [
        {
          "clientId": "reverse-proxy-client",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "reverse-proxy-secret",
          "redirectUris": [
            "http://auth-oidc.test/*",
            "http://auth-oidc.test/oauth2callback",
            "http://auth-keycloak.test/*",
            "http://auth-keycloak.test/oauth2callback"
          ],
          "webOrigins": [
            "*"
          ],
          "protocol": "openid-connect",
          "publicClient": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": true
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "user",
            "description": "Regular user role"
          },
          {
            "name": "admin",
            "description": "Administrator role"
          }
        ]
      },
      "users": [
        {
          "username": "testuser",
          "email": "test@example.com",
          "enabled": true,
          "firstName": "Test",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "password",
              "temporary": false
            }
          ],
          "realmRoles": ["user"]
        },
        {
          "username": "admin",
          "email": "admin@example.com",
          "enabled": true,
          "firstName": "Admin",
          "lastName": "User",
          "credentials": [
            {
              "type": "password",
              "value": "admin",
              "temporary": false
            }
          ],
          "realmRoles": ["admin", "user"]
        }
      ]
    } 