apiVersion: v1
kind: ServiceAccount
metadata:
  name: wireguard-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wireguard-privileged
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wireguard-privileged-binding
subjects:
- kind: ServiceAccount
  name: wireguard-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: wireguard-privileged
  apiGroup: rbac.authorization.k8s.io 